server:
  port: 9000
  compression:
    enabled: true

spring:
  jpa:
    properties:
      hibernate:
        type: trace
        format_sql: true
        show-sql: true
    show-sql: true
  application:
    name: apichat

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 86400000


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    defaults:
      enabled: false
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always
---

spring.profiles: dev-docker

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/apichat?autoReconnect=true&useSSL=false
    username: apichat
    password: temporal

---

spring.profiles: dev-server

spring:
  datasource:
    url: jdbc:mysql://192.168.1.210:3306/apichat?autoReconnect=true&useSSL=false
    username: apichat
    password: temporal