spring:
  application:
    name: apichat


---

spring.profiles: dev-docker

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/apichat?autoReconnect=true&useSSL=false
    username: apichat
    password: temporal

---

spring.profiles: dev-server

spring:
  datasource:
    url: jdbc:mysql://192.168.1.210:3306/apichat?autoReconnect=true&useSSL=false
    username: apichat
    password: temporal